# Generated by Django 4.1.4 on 2022-12-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_issue_call',
            field=models.ManyToManyField(blank=True, help_text='Vytvoreni tridy pro issues', null=True, to='app.issues_class', verbose_name='trida pro issue'),
        ),
    ]
