# Generated by Django 4.1.3 on 2022-11-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_issues_class_class_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='class_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/Issue/%Y/%m/%d/', verbose_name='Ilustracni foto'),
        ),
        migrations.AlterField(
            model_name='issues_class',
            name='class_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/Issue_class/%Y/%m/%d/', verbose_name='Ilustracni foto'),
        ),
    ]
