# Generated by Django 4.1.3 on 2022-11-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_surname',
        ),
    ]
