# Generated by Django 4.1.4 on 2022-12-13 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_assessement_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessement',
            name='as_percent',
            field=models.FloatField(blank=True, help_text=' Zadejte hodnoceni v procentech', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Procenta hodnoceni'),
        ),
    ]
