# Generated by Django 4.1.4 on 2022-12-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_assessement_as_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='deadline',
            field=models.DateField(blank=True, help_text='Zadejte, dokdy musi byt issue zhotoven', null=True, verbose_name='datum'),
        ),
    ]
