# Generated by Django 4.1.3 on 2022-11-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_profile_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_project',
            field=models.ManyToManyField(blank=True, help_text='Na jakem projektu bude pracovat', null=True, to='app.project', verbose_name='projekt'),
        ),
    ]
