# Generated by Django 4.1.3 on 2022-11-20 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_remove_issues_issue_color_issues_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_name', models.CharField(help_text='Zadejte jmeno uzivatele', max_length=45, verbose_name='Jmeno')),
                ('profile_surname', models.CharField(help_text='Zadejte prijmeni uzivatele', max_length=45, verbose_name='Prijmeni')),
                ('profile_git', models.CharField(help_text='Zadejte link na github', max_length=200, verbose_name='Github')),
                ('profile_time', models.TimeField(blank=True, help_text='Zadejte cas straveny na projektu', null=True, verbose_name='Cas')),
                ('profile_foto', models.ImageField(blank=True, null=True, upload_to='uploads/Profile_images/%Y/%m/%d/', verbose_name='Profilova fotografie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
