# Generated by Django 4.1.4 on 2022-12-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_issues_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues_class',
            name='issues_class',
            field=models.ManyToManyField(blank=True, help_text='Pridat issue', null=True, to='app.issues', verbose_name='issues'),
        ),
    ]
