# Generated by Django 4.1.3 on 2022-11-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_profile_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues_class',
            name='project_id',
        ),
        migrations.AddField(
            model_name='project',
            name='project_issue_call',
            field=models.ManyToManyField(help_text='Vytvoreni tridy pro issues', to='app.issues_class', verbose_name='projekt'),
        ),
    ]
