# Generated by Django 4.1.3 on 2022-11-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_issues_class_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='issues_class',
        ),
        migrations.AddField(
            model_name='issues_class',
            name='issues_class',
            field=models.ManyToManyField(help_text='Pridat issue', to='app.issues', verbose_name='issues'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='is_done',
            field=models.BooleanField(default=False, help_text='Je Issue hotov? ANO, NE', verbose_name='Hotov'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_issue_call',
            field=models.ManyToManyField(help_text='Vytvoreni tridy pro issues', to='app.issues_class', verbose_name='trida pro issue'),
        ),
    ]
