# Generated by Django 4.1.4 on 2022-12-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_class_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TIMESPEND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(blank=True, help_text='Zadejte pocet hodin stravenych na projektu', null=True, verbose_name='Cas')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='Zvolte zda je uživatel programátor, nebo síťař', max_length=30, verbose_name='Třída')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='class_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_time',
        ),
        migrations.AddField(
            model_name='profile',
            name='pro_class',
            field=models.CharField(blank=True, choices=[('Programmer', 'Programmer'), ('Networker', 'Networker')], default='Programmer', help_text='Zvolte zda je uživatel programátor, nebo síťař', max_length=30, verbose_name='Třída'),
        ),
        migrations.AddField(
            model_name='project',
            name='types',
            field=models.CharField(blank=True, choices=[('hardware', 'hardware'), ('software', 'software')], default='software', help_text='Zvolte, zda projekt bude softwarový, nebo hardwarový', max_length=30, verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_time_spend',
            field=models.ManyToManyField(blank=True, help_text='Kolik hodin a za jaký měsíc chcete přidat?', null=True, to='app.timespend', verbose_name='čas'),
        ),
    ]
