# Generated by Django 4.1.4 on 2022-12-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_timespend_remove_profile_class_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_profile',
            field=models.CharField(blank=True, help_text='Zadejte id studenta', max_length=10, unique=True, verbose_name='priklad:it1987'),
        ),
    ]
