# Generated by Django 3.2 on 2023-01-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230105_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Jste učitel, nebo student? ANO, NE', verbose_name='Učitel'),
        ),
    ]
