# Generated by Django 3.2 on 2023-01-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, choices=[('javascript', 'javascript'), ('python', 'python'), ('C', 'C'), ('C++', 'C++'), ('java', 'java'), ('kotlin', 'kotlin'), ('PHP', 'PHP'), ('DOCKER', 'DOCKER'), ('jine', 'jine')], default='jine', help_text='Zvolte, zda projekt bude softwarový, nebo hardwarový', max_length=30, verbose_name='Typ'),
        ),
    ]
