# Generated by Django 3.2 on 2023-01-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_project_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=500)),
                ('time_comment', models.DateTimeField(auto_now_add=True)),
                ('profile_comment', models.ManyToManyField(blank=True, help_text='Kdo komentář napsal', null=True, to='app.PROFILE', verbose_name='uživatel')),
            ],
        ),
    ]
