# Generated by Django 3.2 on 2023-01-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_comment_profile_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LANGUAGES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='jine', help_text='Zadejte programovací jazyky', max_length=30, verbose_name='jazyk')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='language',
        ),
        migrations.AlterField(
            model_name='comment',
            name='profile_comment',
            field=models.ManyToManyField(blank=True, help_text='Kdo komentář napsal', null=True, to='app.PROFILE', verbose_name='uživatel'),
        ),
        migrations.AddField(
            model_name='project',
            name='pro_language',
            field=models.ManyToManyField(to='app.LANGUAGES'),
        ),
    ]
