# Generated by Django 3.2 on 2023-01-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20230107_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile_comment',
            field=models.ManyToManyField(blank=True, help_text='Kdo komentář napsal', null=True, to='app.PROFILE', verbose_name='uživatel'),
        ),
    ]
